server.port=8180

# --- Eureka service discovery ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# JWT Secret
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7dc524f22c153833b3d1b700f14d9b4
jwt.expiration=86400000
