server.port=8180

# --- Eureka service discovery ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# JWT Secret
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a7dc524f22c153833b3d1b700f14d9b4
jwt.expiration=86400000

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/microAir_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Default Admin Credentials
admin.username=admin
admin.password=admin123
admin.name=Admin User
admin.role=admin
