spring.application.name=arfoms1


server.port=8083

# Configured URL with timezone, SSL disabled, and auto-create DB if missing
spring.datasource.url=jdbc:mysql://localhost:3306/arfoms_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
# Change this value to your local MySQL root password
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Hibernate auto-validation ensures the database schema perfectly matches Java entities [cite: 15]
spring.jpa.hibernate.ddl-auto=update

# Logs SQL statements cleanly to the console for easier troubleshooting and module verification
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true