package com.genc.arfoms1.model;

import java.util.List;

public final class IndianAirports {

    public record Airport(String code, String city) {}

    private IndianAirports() {}

    public static final List<Airport> AIRPORTS = List.of(
            new Airport("DEL", "Delhi"),
            new Airport("BOM", "Mumbai"),
            new Airport("BLR", "Bengaluru"),
            new Airport("MAA", "Chennai"),
            new Airport("CCU", "Kolkata"),
            new Airport("HYD", "Hyderabad"),
            new Airport("COK", "Kochi"),
            new Airport("AMD", "Ahmedabad"),
            new Airport("PNQ", "Pune"),
            new Airport("GOI", "Goa (Dabolim)"),
            new Airport("GOX", "Goa (Mopa)"),
            new Airport("JAI", "Jaipur"),
            new Airport("LKO", "Lucknow"),
            new Airport("PAT", "Patna"),
            new Airport("TRV", "Thiruvananthapuram"),
            new Airport("CCJ", "Kozhikode"),
            new Airport("IXC", "Chandigarh"),
            new Airport("NAG", "Nagpur"),
            new Airport("VNS", "Varanasi"),
            new Airport("BBI", "Bhubaneswar"),
            new Airport("GAU", "Guwahati"),
            new Airport("IXB", "Bagdogra"),
            new Airport("SXR", "Srinagar"),
            new Airport("IXJ", "Jammu"),
            new Airport("ATQ", "Amritsar"),
            new Airport("IDR", "Indore"),
            new Airport("BHO", "Bhopal"),
            new Airport("RPR", "Raipur"),
            new Airport("VTZ", "Visakhapatnam"),
            new Airport("VGA", "Vijayawada"),
            new Airport("TIR", "Tirupati"),
            new Airport("CJB", "Coimbatore"),
            new Airport("IXM", "Madurai"),
            new Airport("TRZ", "Tiruchirappalli"),
            new Airport("MLR", "Mangaluru"),
            new Airport("IXE", "Mangalore"),
            new Airport("HBX", "Hubli"),
            new Airport("IXR", "Ranchi"),
            new Airport("DBR", "Dehradun"),
            new Airport("DED", "Dehradun (Jolly Grant)"),
            new Airport("IXA", "Agartala"),
            new Airport("IMF", "Imphal"),
            new Airport("DIB", "Dibrugarh"),
            new Airport("JLR", "Jabalpur"),
            new Airport("UDR", "Udaipur"),
            new Airport("JDH", "Jodhpur"),
            new Airport("STV", "Surat"),
            new Airport("RAJ", "Rajkot"),
            new Airport("BDQ", "Vadodara"),
            new Airport("KNU", "Kanpur"),
            new Airport("GWL", "Gwalior"),
            new Airport("AYJ", "Ayodhya"),
            new Airport("PGH", "Prayagraj"),
            new Airport("IXZ", "Port Blair"),
            new Airport("LEH", "Leh"),
            new Airport("SAG", "Shirdi"),
            new Airport("KLH", "Kolhapur"),
            new Airport("IXU", "Aurangabad"),
            new Airport("NDC", "Nanded"),
            new Airport("BEK", "Bareilly"),
            new Airport("AGR", "Agra"),
            new Airport("DHM", "Dharamshala"),
            new Airport("KUU", "Kullu"),
            new Airport("SLV", "Shimla"),
            new Airport("PYG", "Pakyong (Gangtok)"),
            new Airport("TEZ", "Tezpur"),
            new Airport("JRH", "Jorhat"),
            new Airport("SHL", "Shillong"),
            new Airport("DMU", "Dimapur"),
            new Airport("AJL", "Aizawl"),
            new Airport("RUP", "Rupsi"),
            new Airport("HSS", "Hisar")
    );
}

