package com.genc.arfoms.loyalty.dto;

import com.genc.arfoms.loyalty.model.MembershipTier;

import java.util.List;

/**
 * The set of offers generated by the loyalty manager for a given flight
 * distance, together with the base miles the member would earn.
 */
public record LoyaltyOffersResponse(
        Long memberId,
        double distanceMiles,
        int baseMilesEarned,
        MembershipTier membershipTier,
        List<LoyaltyOffer> offers) {
}

